### PR TITLE
Add parameter to DIVA Protocol query

### PR DESCRIPTION
**Pull request by oraclown**
Adds `divaDiamond` as the second query parameter:
    - description: Contract address of DIVA Protocol (since there might be multiple deployments on a single network, e.g. `0xebBAA31B1Ebd727A1a42e71dC15E304aD8905211`)
    - value type: `address`

### CODE REVIEW

**Comment by tkernell** [comment]
Don't we want to include the network id as a parameter?

**Comment by oraclown** [comment]
> Don't we want to include the network id as a parameter?

I thought @Walodja1987 didn't want that

**Comment by oraclown** [comment]
This seems to make the most sense:

- remove network specifics from the query name
- include chain id as a query parameter

So we can use one query type that will produce unique queryData/queryIds for multiple DIVA Protocol deployments on the same and different networks

**Review by tkernell — APPROVED** [review]

**Comment by tkernell** [comment]
Looks good!

**Pull request merged**
