### PR TITLE
Create ChatGPTResponse.md

### LINKED ISSUE #92: [New Query Type]: ChatGPTResponse
### Contact Details

t.j.wies@gmail.com

### Query Type Name

ChatGPTResponse

### Description

This query type will be used to put ChatGPT responses to prompts on chain for use by other smart contracts.
It will accept a `string memory`, its prompt, and return a `string memory`, its GPTchat answer.

### Your query parameters

- prompt
    - description: the prompt the reporter will put in ChatGPT
    - value type: `string memory`

### Your response type

response type: `string memory`

### PR DESCRIPTION
**Pull request by tallywiesenberg**
Closes #92

### CODE REVIEW

**Comment by themandalore** [comment]
can you add an example?

**Comment by tallywiesenberg** [comment]
yes, will also add a prompt for example in the issue template

**Comment by themandalore** [comment]
can you put the example response and show how to encode it?

**Comment by tallywiesenberg** [comment]
@themandalore , yes, and added dispute considerations and suggested data source

**Review by themandalore — APPROVED** [review]

**Pull request merged**
