### PR TITLE
FilecoinCID

### PR DESCRIPTION
**Pull request by 0xSpuddy**
A proposed query type for reporting Filecoin CIDs generated from the data found at a URL for some IPFS data.

### CODE REVIEW

**Comment by tkernell** [comment]
I would just get rid of the ipfs.io gateway examples, and also show an example encoded response

**Comment by 0xSpuddy** [comment]
changed it to be one consistent example throughout, and added reporter response

**Comment by 0xSpuddy** [comment]
does it make sense to call this query type something like "ipfsCID" instead of "FilecoinCID"?

**Comment by lordshashank** [comment]
I think, It would be better to put something like just ```FileCID```

**Review by themandalore — APPROVED** [review]

**Comment by 0xSpuddy** [comment]
@lordshashank do you need anything else to move forward with an integration? let us know, happy to help

**Pull request merged**
