### PR TITLE
Proposal for EVMCall data type

### PR DESCRIPTION
**Pull request by tallywiesenberg**
I wrote up a data type that can read data and bridge it over from one chain to another. Thoughts welcome!

### CODE REVIEW

**Comment by themandalore** [comment]
Looks great.  Before I merge though, any thoughts on how to handle changing variables?  Should we return a block.number or a block.timestamp with it?  The problem is thing like say balance. It could be one thing at one block, the oracle grabs the data and then they transfer before the other chain even knows about it....

**Comment by brendaloya** [comment]
I agree, adding the time stamp or block number would be helpful.

**Comment by tallywiesenberg** [comment]
Great point, timestamp is a great addition

**Comment by themandalore** [comment]
i would actually flip it...have it return a timestamp of when it was queried.  AFAIK, querying the chain by timestamp is super tough and could be pretty limiting for the node providers

**Review by themandalore — APPROVED** [review]

**Pull request merged**
